[修正] 各種リファクタ
114514K/discoxy pull request #14
Opened 2020-10-12 15:53 UTC by Colk-tech

ロジックやデータ構造は変わっていません

2020-10-12 16:02 UTC, Colk-tech commented
@loxygenK ready for review

2020-10-12 16:13 UTC, loxygenK approved these changes
この後のPRでProxySettingに変更を加えてDiscordのパスを保存するようにしたい（僕がやります）

2020-10-12 16:20 UTC, loxygenK requested changes
ごめんなさい撤回します
それと、`discord_entry.py`でモジュール解決に失敗してるのでそこの修正もお願いしたい:bow:

2020-10-12 16:20 UTC, loxygenK commented on lib/controller/utils.py
> +    return os.environ[environ_name]
modelで使ってるutil関数なんでcontrollerに持ってきたの

2020-10-12 22:54 UTC, Colk-tech commented on lib/controller/utils.py
> +    return os.environ[environ_name]
ア！気づきませんでした

2020-10-12 22:54 UTC, Colk-tech commented on lib/controller/utils.py
> +    return os.environ[environ_name]
生きててごめんね...

2020-10-13 02:48 UTC, loxygenK approved these changes
***†あっｐろゔぇ†***

2020-10-13 03:32 UTC, merged