[WIP] 動的に値を受け取れるようにした
114514K/discoxy pull request #8
Opened 2020-10-09 09:22 UTC by Colk-tech

2020-10-09 15:02 UTC, Colk-tech commented
@loxygenK それなりにできたから見てみてくれ〜〜〜〜

2020-10-09 15:02 UTC, Colk-tech commented
あとはバックとフロントをつなげます

2020-10-09 23:11 UTC, Colk-tech commented
WIPはずれた

2020-10-10 08:37 UTC, loxygenK requested changes
***low acceptability with confirmation of bug...***
P.S. 利用者層を考えてエラーメッセージを日本語izeしました
日本人、日本語のほうが見やすい

2020-10-10 08:37 UTC, loxygenK commented on lib/model/parser.py
> +        utils.error_dialog("Invalid address has passed. Please specify valid URL.")
```suggestion
        utils.error_dialog("アドレスが無効です。正しいURLを入力してください。")
```

2020-10-10 08:37 UTC, loxygenK commented on lib/model/parser.py
> +        return False
```suggestion
    if not port.isnumeric():
        utils.error_dialog("ポート番号は数値で入力してください。")
        return False

    if not (0 <= int(port) <= 65535):
        utils.error_dialog("ポート番号が無効です。0〜65535の間で指定してください。")
        return False
```

2020-10-10 08:37 UTC, loxygenK commented on lib/model/parser.py
> +        return False
```suggestion
    if not os.path.exists(place):
        utils.error_dialog("File not found. Please check your file.")
        return False
```

2020-10-10 08:37 UTC, loxygenK commented on lib/utils.py
> +    showerror(message=message)
これいる？

2020-10-10 08:37 UTC, loxygenK commented on lib/utils.py
> +
うーん、`utils.py`の中にいろんなレイヤーのユーティリティが混ざってしまったな、あとで分割しましょう

2020-10-10 09:49 UTC, Colk-tech commented on lib/utils.py
> +
#12 （切り出し）

2020-10-10 09:50 UTC, Colk-tech commented on lib/utils.py
> +    showerror(message=message)
よくよく考えたらいらんわ草

2020-10-10 09:53 UTC, Colk-tech commented on lib/utils.py
> +    showerror(message=message)
直したらコンフリクトしそうなので別のissueに切り出しです
#13

2020-10-10 09:54 UTC, Colk-tech commented
れ゛びゅ゛ー゛お゛い゛じい゛

2020-10-10 10:33 UTC, Colk-tech commented
@loxygenK 
とりあえずissue切り出しました
OKですか？

2020-10-10 11:17 UTC, loxygenK approved these changes
すき

2020-10-10 11:25 UTC, merged